[package]
name = "mtls-sys"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Low-level FFI bindings for the mTLS C library"
links = "mtls"
build = "build.rs"

[build-dependencies]
bindgen = "0.70"

[dependencies]
libc = "0.2"
